### ISSUE TITLE
Update to 1.19?

### ISSUE THREAD

**Issue by jaredniegas** [StoneLabs/strains-of-ascension#8]
Just watched the first season of Made in Abyss before finding this and I really want this to be updated soon!

**Comment by jaredniegas** [comment]
`[10:57:11] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.19-loader.0.14.8-launcher.0.11.0.jar:0.11.0]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1805 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.item.Item.fromBlock(Item:74) ~[?:?]
	at net.minecraft.block.Block.asItem(Block:554) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.createAndRegister(FlatLevelGeneratorPresets:60) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.handler$bce000$bcl_run(FlatLevelGeneratorPresets:545) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.initAndGetDefault(FlatLevelGeneratorPresets) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets.initAndGetDefault(FlatLevelGeneratorPresets:199) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.9.2-e6dc3f57e28b7f8c.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.item.Item.fromBlock(Item:74) ~[?:?]
	at net.minecraft.block.Block.asItem(Block:554) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.createAndRegister(FlatLevelGeneratorPresets:60) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.handler$bce000$bcl_run(FlatLevelGeneratorPresets:545) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.initAndGetDefault(FlatLevelGeneratorPresets) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets.initAndGetDefault(FlatLevelGeneratorPresets:199) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 4 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector injectedClearStatusEffects(Lnet/minecraft/class_1309;)Z in strainsofascension.mixins.json:MilkBucketMixin from mod strainsofascension failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap strains_of_ascension-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:77) ~[libjf-unsafe-v0-2.9.2-e6dc3f57e28b7f8c.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.item.Item.fromBlock(Item:74) ~[?:?]
	at net.minecraft.block.Block.asItem(Block:554) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.createAndRegister(FlatLevelGeneratorPresets:60) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.handler$bce000$bcl_run(FlatLevelGeneratorPresets:545) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets$Registrar.initAndGetDefault(FlatLevelGeneratorPresets) ~[?:?]
	at net.minecraft.world.gen.FlatLevelGeneratorPresets.initAndGetDefault(FlatLevelGeneratorPresets:199) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_44104(BuiltinRegistries:98) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries:105) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries:104) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:326) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:50) ~[?:?]
	at net.minecraft.server.Main.main(Main:98) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 4 more`

**Comment by StoneLabs** [comment]
My wrists are currently injured, so I can't in the following weeks, but I'm probably doing it after that.

**Comment by StoneLabs** [comment]
I finally got to it. Should work fine but I've done little testing.

~stone
